# Generated by Django 6.1 on 2026-08-14 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="times_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(
                default=0, help_text="0 = unlimited uses"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                blank=True, help_text="Leave blank for no expiry", null=True
            ),
        ),
    ]
