# Generated by Django 6.1 on 2026-08-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_razorpay_order_id_order_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkOrderInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("product_name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=10)),
                (
                    "target_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total budget in INR",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("delivery_pincode", models.CharField(blank=True, max_length=20)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("contacted", "Contacted / In Discussion"),
                            ("quoted", "Quote Sent"),
                            ("completed", "Completed"),
                            ("cancelled", "Closed / Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Bulk Order Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="is_confirmed",
            field=models.BooleanField(
                default=False, help_text="For COD order verification"
            ),
        ),
    ]
